### ISSUE TITLE
Is the codebase self-contained?

### ISSUE THREAD

**Issue by vingstar** [facebookresearch/fbpcp#194]
Hi, 
I have tried to understand your codebase for a while, and I find that some abstract interfaces, such as these in  `fbpcp/repository`, are not implemented concretely.  I know the functionality of these components after reading your docs, but I just wonder  whether the codebase can be used on its own, since these interfaces are called in the public interface `MPCService`.

**Comment by vingstar** [comment]
I found these abstract interfaces are implemented in upper application of  https://github.com/facebookresearch/fbpcs, so the issue seems resolved.

**Comment by zhuang-93** [comment]
Hi Junjie, thanks for your interest in the repository. Our repository is following the principles:
1. Core entity should be a plain object which represents data only
2. repository should maintain a different entity which takes care of serialization/deserialization
3. mapper is to transform between entities for decoupling data and business logic

So we provide interfaces to our users. They will take the responsibility to map MPCInstance to their custom object and repositories will do the serialization/deserialization during CRUD operations.

**Comment by zhuang-93** [comment]
> I found these abstract interfaces are implemented in upper application of https://github.com/facebookresearch/fbpcs, so the issue seems resolved.

Yes fbpcs is the upstream caller of fbpcp and they have their own repository to do the data manipulation.

**Comment by vingstar** [comment]
> So we provide interfaces to our users. They will take the responsibility to map MPCInstance to their custom object and repositories will do the serialization/deserialization during CRUD operations.

Got it, thank you for your quick reply.
